import type { LetterEntry } from './letter-data';

// Metro requires static require() paths — no dynamic require allowed.
// Each file maps to one "Narysuj duże/małe X" prompt.

const AUDIO: Record<string, Record<string, number>> = {
  duze: {
    'a':        require('../../assets/sounds/letter-trace/narysuj-duze-a.mp3'),
    'a-ogonek': require('../../assets/sounds/letter-trace/narysuj-duze-a-ogonek.mp3'),
    'b':        require('../../assets/sounds/letter-trace/narysuj-duze-b.mp3'),
    'c':        require('../../assets/sounds/letter-trace/narysuj-duze-c.mp3'),
    'c-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-c-kreska.mp3'),
    'd':        require('../../assets/sounds/letter-trace/narysuj-duze-d.mp3'),
    'e':        require('../../assets/sounds/letter-trace/narysuj-duze-e.mp3'),
    'e-ogonek': require('../../assets/sounds/letter-trace/narysuj-duze-e-ogonek.mp3'),
    'f':        require('../../assets/sounds/letter-trace/narysuj-duze-f.mp3'),
    'g':        require('../../assets/sounds/letter-trace/narysuj-duze-g.mp3'),
    'h':        require('../../assets/sounds/letter-trace/narysuj-duze-h.mp3'),
    'i':        require('../../assets/sounds/letter-trace/narysuj-duze-i.mp3'),
    'j':        require('../../assets/sounds/letter-trace/narysuj-duze-j.mp3'),
    'k':        require('../../assets/sounds/letter-trace/narysuj-duze-k.mp3'),
    'l':        require('../../assets/sounds/letter-trace/narysuj-duze-l.mp3'),
    'l-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-l-kreska.mp3'),
    'm':        require('../../assets/sounds/letter-trace/narysuj-duze-m.mp3'),
    'n':        require('../../assets/sounds/letter-trace/narysuj-duze-n.mp3'),
    'n-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-n-kreska.mp3'),
    'o':        require('../../assets/sounds/letter-trace/narysuj-duze-o.mp3'),
    'o-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-o-kreska.mp3'),
    'p':        require('../../assets/sounds/letter-trace/narysuj-duze-p.mp3'),
    'r':        require('../../assets/sounds/letter-trace/narysuj-duze-r.mp3'),
    's':        require('../../assets/sounds/letter-trace/narysuj-duze-s.mp3'),
    's-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-s-kreska.mp3'),
    't':        require('../../assets/sounds/letter-trace/narysuj-duze-t.mp3'),
    'u':        require('../../assets/sounds/letter-trace/narysuj-duze-u.mp3'),
    'w':        require('../../assets/sounds/letter-trace/narysuj-duze-w.mp3'),
    'y':        require('../../assets/sounds/letter-trace/narysuj-duze-y.mp3'),
    'z':        require('../../assets/sounds/letter-trace/narysuj-duze-z.mp3'),
    'z-kreska': require('../../assets/sounds/letter-trace/narysuj-duze-z-kreska.mp3'),
    'z-kropka': require('../../assets/sounds/letter-trace/narysuj-duze-z-kropka.mp3'),
  },
  male: {
    'a':        require('../../assets/sounds/letter-trace/narysuj-male-a.mp3'),
    'a-ogonek': require('../../assets/sounds/letter-trace/narysuj-male-a-ogonek.mp3'),
    'b':        require('../../assets/sounds/letter-trace/narysuj-male-b.mp3'),
    'c':        require('../../assets/sounds/letter-trace/narysuj-male-c.mp3'),
    'c-kreska': require('../../assets/sounds/letter-trace/narysuj-male-c-kreska.mp3'),
    'd':        require('../../assets/sounds/letter-trace/narysuj-male-d.mp3'),
    'e':        require('../../assets/sounds/letter-trace/narysuj-male-e.mp3'),
    'e-ogonek': require('../../assets/sounds/letter-trace/narysuj-male-e-ogonek.mp3'),
    'f':        require('../../assets/sounds/letter-trace/narysuj-male-f.mp3'),
    'g':        require('../../assets/sounds/letter-trace/narysuj-male-g.mp3'),
    'h':        require('../../assets/sounds/letter-trace/narysuj-male-h.mp3'),
    'i':        require('../../assets/sounds/letter-trace/narysuj-male-i.mp3'),
    'j':        require('../../assets/sounds/letter-trace/narysuj-male-j.mp3'),
    'k':        require('../../assets/sounds/letter-trace/narysuj-male-k.mp3'),
    'l':        require('../../assets/sounds/letter-trace/narysuj-male-l.mp3'),
    'l-kreska': require('../../assets/sounds/letter-trace/narysuj-male-l-kreska.mp3'),
    'm':        require('../../assets/sounds/letter-trace/narysuj-male-m.mp3'),
    'n':        require('../../assets/sounds/letter-trace/narysuj-male-n.mp3'),
    'n-kreska': require('../../assets/sounds/letter-trace/narysuj-male-n-kreska.mp3'),
    'o':        require('../../assets/sounds/letter-trace/narysuj-male-o.mp3'),
    'o-kreska': require('../../assets/sounds/letter-trace/narysuj-male-o-kreska.mp3'),
    'p':        require('../../assets/sounds/letter-trace/narysuj-male-p.mp3'),
    'r':        require('../../assets/sounds/letter-trace/narysuj-male-r.mp3'),
    's':        require('../../assets/sounds/letter-trace/narysuj-male-s.mp3'),
    's-kreska': require('../../assets/sounds/letter-trace/narysuj-male-s-kreska.mp3'),
    't':        require('../../assets/sounds/letter-trace/narysuj-male-t.mp3'),
    'u':        require('../../assets/sounds/letter-trace/narysuj-male-u.mp3'),
    'w':        require('../../assets/sounds/letter-trace/narysuj-male-w.mp3'),
    'y':        require('../../assets/sounds/letter-trace/narysuj-male-y.mp3'),
    'z':        require('../../assets/sounds/letter-trace/narysuj-male-z.mp3'),
    'z-kreska': require('../../assets/sounds/letter-trace/narysuj-male-z-kreska.mp3'),
    'z-kropka': require('../../assets/sounds/letter-trace/narysuj-male-z-kropka.mp3'),
  },
};

export function getPromptAudio(entry: LetterEntry): number {
  return AUDIO[entry.caze][entry.audioKey];
}
